require_relative 'archive_extensions/languages'
require_relative 'archive_extensions/language_activity'
require_relative 'archive_extensions/language_breakdown'
require_relative 'archive_extensions/repository_ranking_update'
require_relative 'archive_extensions/top_active_repositories'
require_relative 'archive_extensions/top_active_developers'
require_relative 'archive_extensions/top_contributed_repositories'
require_relative 'archive_extensions/user_ranking_update'
require_relative 'archive_extensions/compare_users'
require_relative 'archive_extensions/similar_users'
require_relative 'archive_extensions/user_activity'

module ArchiveExtensions

end
